# Generated by Django 5.1.7 on 2025-03-20 14:14

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='baslik', unique=True, verbose_name='Slug'),
        ),
    ]
