# Generated by Django 5.1.7 on 2025-03-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_video_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='kapak_resmi',
            field=models.ImageField(default=0, upload_to='medias/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='video_dosyasi',
            field=models.FileField(upload_to='medias/', verbose_name='Video Dosyası'),
        ),
    ]
