# Generated by Django 5.1.7 on 2025-03-20 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='kategori',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='videolar', to='webapp.kategori', verbose_name='Kategori'),
            preserve_default=False,
        ),
    ]
